insert into menu_menu (id, name)  values ('Clientes');
insert into menu_menu values ('Ventas');
insert into menu_menu (id, name) values ('Inventarios');
insert into menu_menu (name) values ('Proveedores');
insert into menu_menu (name) values ('Compras');
insert into menu_menu (name) values ('Estadisticas');
insert into menu_menu (name) values ('Procesos');
insert into menu_menu (name) values ('Herramientas');
insert into menu_menu (name) values ('Configuración');
insert into roles_roles (name) values ('Administrador');
insert into roles_roles (name) values ('Almacen');
insert into roles_roles (name) values ('Cobranza');
insert into roles_roles  (name) values ('Compras');
insert into roles_roles (name) values ('Contabilidad');
insert into roles_roles (name) values ('Facturista');
insert into roles_roles (name) values ('Gerencia');
insert into roles_roles (name) values ('Mostrador');
insert into roles_roles (name) values ('Pagos');
insert into roles_roles (name) values ('Ventas');

