# Generated by Django 4.2 on 2024-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_register_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_duration',
            field=models.IntegerField(default=3600),
        ),
    ]
