# Generated by Django 4.2 on 2024-04-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_optionmenu_options_alter_optionmenu_link_url'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='menu.menu'),
        ),
    ]
